// Code generated by "stringer -type=BinaryOperator"; DO NOT EDIT.

package laks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BO_ADD-0]
	_ = x[BO_MINUS-1]
	_ = x[BO_MULT-2]
	_ = x[BO_DIV-3]
}

const _BinaryOperator_name = "BO_ADDBO_MINUSBO_MULTBO_DIV"

var _BinaryOperator_index = [...]uint8{0, 6, 14, 21, 27}

func (i BinaryOperator) String() string {
	if i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
