// Code generated by "stringer -type=ExpressionType"; DO NOT EDIT.

package laks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[E_LIT-0]
	_ = x[E_OP-1]
}

const _ExpressionType_name = "E_LITE_OP"

var _ExpressionType_index = [...]uint8{0, 5, 9}

func (i ExpressionType) String() string {
	if i >= ExpressionType(len(_ExpressionType_index)-1) {
		return "ExpressionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpressionType_name[_ExpressionType_index[i]:_ExpressionType_index[i+1]]
}
