// Code generated by "stringer -type=StatementType"; DO NOT EDIT.

package laks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ST_PRINT-0]
	_ = x[ST_BINEXPR-1]
	_ = x[ST_LIT-2]
}

const _StatementType_name = "ST_PRINTST_BINEXPRST_LIT"

var _StatementType_index = [...]uint8{0, 8, 18, 24}

func (i StatementType) String() string {
	if i >= StatementType(len(_StatementType_index)-1) {
		return "StatementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatementType_name[_StatementType_index[i]:_StatementType_index[i+1]]
}
