// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package laks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T_INT-0]
	_ = x[T_SEMI-1]
	_ = x[T_MULT-2]
	_ = x[T_ADD-3]
}

const _TokenType_name = "T_INTT_SEMIT_MULTT_ADD"

var _TokenType_index = [...]uint8{0, 5, 11, 17, 22}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
