// Code generated by "stringer -type=ValueType"; DO NOT EDIT.

package laks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VAL_INT-0]
	_ = x[VAL_TRUE-1]
	_ = x[VAL_FALSE-2]
	_ = x[VAL_STRING-3]
}

const _ValueType_name = "VAL_INTVAL_TRUEVAL_FALSEVAL_STRING"

var _ValueType_index = [...]uint8{0, 7, 15, 24, 34}

func (i ValueType) String() string {
	if i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
